   create table comment_likes (
        comment_id bigint,
        id bigint generated by default as identity,
        likes_clicker_id bigint not null,
        primary key (id)
    )
    create table crop_bookmarks (
        bookmark_owner_id bigint,
        crop_post_id bigint not null,
        id bigint generated by default as identity,
        primary key (id)
    )
    create table crop_images (
        crop_posts__id bigint,
        id bigint generated by default as identity,
        image_url varchar(255),
        primary key (id)
    )
    create table crop_posts (
        created_date date not null,
        price integer not null,
        price_proposal boolean not null,
        bookmark_count bigint not null,
        buyer_id bigint,
        created_at timestamp(6) not null,
        crop_post_author_id bigint not null,
        id bigint generated by default as identity,
        version bigint not null,
        content varchar(255) not null,
        crop_category varchar(255) not null check (crop_category in ('GRAIN','VEGETABLE','FRUIT','BEAN','ETC')),
        title varchar(255) not null,
        trade_status varchar(255) not null check (trade_status in ('TRADED','TRADING','RESERVED')),
        trade_type varchar(255) not null check (trade_type in ('DIRECT_TRADE','DELIVERY_TRADE')),
        primary key (id)
    )
    create table feedback_images (
        created_at timestamp(6) not null,
        feedback_id bigint,
        id bigint generated by default as identity,
        url varchar(255),
        primary key (id)
    )
    create table feedbacks (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint,
        content varchar(255),
        primary key (id)
    )
    create table garden_images (
        garden_id bigint,
        garden_image_id bigint generated by default as identity,
        image_url varchar(255),
        primary key (garden_image_id)
    )
    create table garden_likes (
        created_at timestamp(6) not null,
        garden_id bigint,
        garden_like_id bigint generated by default as identity,
        member_id bigint,
        primary key (garden_like_id)
    )
    create table gardens (
        is_deleted boolean,
        is_equipment boolean,
        is_toilet boolean,
        is_waterway boolean,
        last_modified_date date,
        latitude float(53) not null,
        longitude float(53) not null,
        recruit_end_date date,
        recruit_start_date date,
        reported_score integer,
        use_end_date date,
        use_start_date date,
        created_at timestamp(6) not null,
        garden_id bigint generated by default as identity,
        writer_id bigint,
        address varchar(255) not null,
        contact varchar(255),
        garden_description TEXT,
        garden_name varchar(255) not null,
        garden_status varchar(255) not null check (garden_status in ('ACTIVE','INACTIVE')),
        garden_type varchar(255) not null check (garden_type in ('ALL','PUBLIC','PRIVATE')),
        link_for_request varchar(255),
        price varchar(255),
        size varchar(255),
        point geometry not null,
        primary key (garden_id)
    )
    create table members (
        manner_score integer,
        id bigint generated by default as identity,
        email varchar(255) not null,
        nickname varchar(255),
        role varchar(255) not null check (role in ('USER')),
        sido varchar(255),
        sigungu varchar(255),
        upmyeondong varchar(255),
        primary key (id)
    )
    create table my_managed_gardens (
        use_end_date date,
        use_start_date date,
        garden_id bigint,
        member_id bigint,
        my_managed_garden_id bigint generated by default as identity,
        image_url varchar(255),
        primary key (my_managed_garden_id)
    )
    create table post_comments (
        author_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        likes_count bigint,
        parent_comment_id bigint,
        post_id bigint,
        report_count bigint,
        updated_at timestamp(6),
        version bigint,
        content varchar(255),
        primary key (id)
    )
    create table post_images (
        id bigint generated by default as identity,
        post_id bigint,
        image_url varchar(255),
        primary key (id)
    )
    create table post_likes (
        id bigint generated by default as identity,
        likes_clicker_id bigint,
        post_id bigint not null,
        primary key (id)
    )
    create table posts (
        created_date date,
        comments_count bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        likes_count bigint not null,
        post_author_id bigint not null,
        report_count bigint not null,
        updated_at timestamp(6),
        version bigint not null,
        title varchar(255) not null,
        content clob not null,
        primary key (id)
    )
    create table public_data_gardens (
        farm_id integer,
        row_num integer,
        unique_hash integer,
        id bigint generated by default as identity,
        area_large_category varchar(255),
        area_large_name varchar(255),
        area_medium_category varchar(255),
        area_medium_name varchar(255),
        farm_area_information varchar(255),
        farm_name varchar(255),
        farm_type varchar(255),
        full_address varchar(255),
        offsite_facilities varchar(255),
        registration_date varchar(255),
        sell_area_information varchar(255),
        update_date varchar(255),
        website varchar(255),
        primary key (id)
    )
    create table regions (
        code bigint not null,
        sido varchar(255),
        sigungu varchar(255),
        upmyeondong varchar(255),
        area geometry,
        point geometry,
        primary key (code)
    )
    create table reports (
        created_at timestamp(6) not null,
        garden_id bigint,
        id bigint generated by default as identity,
        reporter_id bigint,
        report_type varchar(31) not null,
        content varchar(255),
        garden_report_type varchar(255) check (garden_report_type in ('FAKED_SALE','SPAMMING','SWEAR_WORD','SENSATIONAL','PERSONAL_INFORMATION_EXPOSURE','COMMENTS')),
        primary key (id)
    )