create table posts
(
    created_date   date,
    delete_status  boolean,
    comments_count bigint       not null,
    created_at     timestamp(6) not null,
    id             bigint generated by default as identity,
    likes_count    bigint       not null,
    post_author_id bigint       not null,
    report_count   bigint       not null,
    updated_at     timestamp(6),
    version        bigint       not null,
    post_type      varchar(255) check (post_type in ('INFORMATION_SHARE', 'GARDEN_SHOWCASE', 'QUESTION', 'ETC')),
    title          varchar(255) not null,
    content        clob         not null,
    primary key (id)
);